import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          .mySpan {
            color: black;
          }
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="/sc.js"></script> */}
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="mySpan">Hunting Coder</span>
        </h1>
        <div className={styles.imagewrap}>
          <Image className={styles.myImg} src="/homeimg.jpg" alt="" width={237} height={158} />
        </div>
        <p className={styles.description}>A blog for coders by a coder.</p>

        <div>
          <h2>Latest Blogs</h2>
          <div className="blogItem1">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur commodi consectetur eos.</p>
          </div>
          <div className="blogItem2">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur commodi consectetur eos.</p>
          </div>
          <div className="blogItem3">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur commodi consectetur eos.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
